name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key and known_hosts
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no root@139.59.65.165 << 'EOF'
            set -e
            cd bms/
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart fe-sever
            pm2 restart http-sever
            pm2 restart ws-sever
          EOF
